import {NgModule} from '@angular/core';
import { CommonModule } from '@angular/common';
import {MatProgressBarModule} from '@angular/material/progress-bar';
import {
   MatTableModule,
   MatMenuModule,
   MatButtonModule,
   MatIconModule,
   MatFormFieldModule,
   MatInputModule,
   MatDatepickerModule,
   MatNativeDateModule,
   MatCheckboxModule,
   MatSidenavModule,
   MatToolbarModule,
   MatListModule,
   MatTabsModule,
   MatCardModule,
   MatSelectModule,
   MatProgressSpinnerModule,
   MatDialogModule,
   MatBadgeModule,
   MatRippleModule,
   MatPaginatorModule,
   MatSnackBarModule,
   MatSortModule
} from '@angular/material';
@NgModule({
  imports: [
    MatTableModule,
    MatMenuModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTabsModule,
    MatCardModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatBadgeModule,
    MatRippleModule,
    MatPaginatorModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatSortModule
  ],
  exports: [
  CommonModule,
   MatToolbarModule,
   MatButtonModule,
   MatCardModule,
   MatInputModule,
   MatTableModule,
   MatMenuModule,
   MatIconModule,
   MatTabsModule,
   MatFormFieldModule,
   MatDatepickerModule,
   MatNativeDateModule,
   MatCheckboxModule,
   MatSidenavModule,
   MatListModule,
   MatSelectModule,
   MatProgressSpinnerModule,
   MatDialogModule,
   MatBadgeModule,
   MatRippleModule,
   MatPaginatorModule,
   MatSnackBarModule,
   MatProgressBarModule,
   MatSortModule
   ],
})
export class MaterialModule { }
